/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/alert/v1alpha1"
	scheme "kubeform.dev/provider-newrelic-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MutingRulesGetter has a method to return a MutingRuleInterface.
// A group's client should implement this interface.
type MutingRulesGetter interface {
	MutingRules(namespace string) MutingRuleInterface
}

// MutingRuleInterface has methods to work with MutingRule resources.
type MutingRuleInterface interface {
	Create(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.CreateOptions) (*v1alpha1.MutingRule, error)
	Update(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (*v1alpha1.MutingRule, error)
	UpdateStatus(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (*v1alpha1.MutingRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MutingRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MutingRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MutingRule, err error)
	MutingRuleExpansion
}

// mutingRules implements MutingRuleInterface
type mutingRules struct {
	client rest.Interface
	ns     string
}

// newMutingRules returns a MutingRules
func newMutingRules(c *AlertV1alpha1Client, namespace string) *mutingRules {
	return &mutingRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the mutingRule, and returns the corresponding mutingRule object, and an error if there is any.
func (c *mutingRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MutingRule, err error) {
	result = &v1alpha1.MutingRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mutingrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MutingRules that match those selectors.
func (c *mutingRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MutingRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MutingRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("mutingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested mutingRules.
func (c *mutingRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("mutingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a mutingRule and creates it.  Returns the server's representation of the mutingRule, and an error, if there is any.
func (c *mutingRules) Create(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.CreateOptions) (result *v1alpha1.MutingRule, err error) {
	result = &v1alpha1.MutingRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("mutingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mutingRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a mutingRule and updates it. Returns the server's representation of the mutingRule, and an error, if there is any.
func (c *mutingRules) Update(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (result *v1alpha1.MutingRule, err error) {
	result = &v1alpha1.MutingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mutingrules").
		Name(mutingRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mutingRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *mutingRules) UpdateStatus(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (result *v1alpha1.MutingRule, err error) {
	result = &v1alpha1.MutingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("mutingrules").
		Name(mutingRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(mutingRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the mutingRule and deletes it. Returns an error if one occurs.
func (c *mutingRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mutingrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *mutingRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("mutingrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched mutingRule.
func (c *mutingRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MutingRule, err error) {
	result = &v1alpha1.MutingRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("mutingrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
