/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/application/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSettingses implements SettingsInterface
type FakeSettingses struct {
	Fake *FakeApplicationV1alpha1
	ns   string
}

var settingsesResource = schema.GroupVersionResource{Group: "application.newrelic.kubeform.com", Version: "v1alpha1", Resource: "settingses"}

var settingsesKind = schema.GroupVersionKind{Group: "application.newrelic.kubeform.com", Version: "v1alpha1", Kind: "Settings"}

// Get takes name of the settings, and returns the corresponding settings object, and an error if there is any.
func (c *FakeSettingses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Settings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(settingsesResource, c.ns, name), &v1alpha1.Settings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Settings), err
}

// List takes label and field selectors, and returns the list of Settingses that match those selectors.
func (c *FakeSettingses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SettingsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(settingsesResource, settingsesKind, c.ns, opts), &v1alpha1.SettingsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SettingsList{ListMeta: obj.(*v1alpha1.SettingsList).ListMeta}
	for _, item := range obj.(*v1alpha1.SettingsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested settingses.
func (c *FakeSettingses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(settingsesResource, c.ns, opts))

}

// Create takes the representation of a settings and creates it.  Returns the server's representation of the settings, and an error, if there is any.
func (c *FakeSettingses) Create(ctx context.Context, settings *v1alpha1.Settings, opts v1.CreateOptions) (result *v1alpha1.Settings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(settingsesResource, c.ns, settings), &v1alpha1.Settings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Settings), err
}

// Update takes the representation of a settings and updates it. Returns the server's representation of the settings, and an error, if there is any.
func (c *FakeSettingses) Update(ctx context.Context, settings *v1alpha1.Settings, opts v1.UpdateOptions) (result *v1alpha1.Settings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(settingsesResource, c.ns, settings), &v1alpha1.Settings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Settings), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSettingses) UpdateStatus(ctx context.Context, settings *v1alpha1.Settings, opts v1.UpdateOptions) (*v1alpha1.Settings, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(settingsesResource, "status", c.ns, settings), &v1alpha1.Settings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Settings), err
}

// Delete takes name of the settings and deletes it. Returns an error if one occurs.
func (c *FakeSettingses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(settingsesResource, c.ns, name), &v1alpha1.Settings{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSettingses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(settingsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SettingsList{})
	return err
}

// Patch applies the patch and returns the patched settings.
func (c *FakeSettingses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Settings, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(settingsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Settings{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Settings), err
}
