/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/events/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeToMetricsRules implements ToMetricsRuleInterface
type FakeToMetricsRules struct {
	Fake *FakeEventsV1alpha1
	ns   string
}

var tometricsrulesResource = schema.GroupVersionResource{Group: "events.newrelic.kubeform.com", Version: "v1alpha1", Resource: "tometricsrules"}

var tometricsrulesKind = schema.GroupVersionKind{Group: "events.newrelic.kubeform.com", Version: "v1alpha1", Kind: "ToMetricsRule"}

// Get takes name of the toMetricsRule, and returns the corresponding toMetricsRule object, and an error if there is any.
func (c *FakeToMetricsRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ToMetricsRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(tometricsrulesResource, c.ns, name), &v1alpha1.ToMetricsRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ToMetricsRule), err
}

// List takes label and field selectors, and returns the list of ToMetricsRules that match those selectors.
func (c *FakeToMetricsRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ToMetricsRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(tometricsrulesResource, tometricsrulesKind, c.ns, opts), &v1alpha1.ToMetricsRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ToMetricsRuleList{ListMeta: obj.(*v1alpha1.ToMetricsRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ToMetricsRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested toMetricsRules.
func (c *FakeToMetricsRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(tometricsrulesResource, c.ns, opts))

}

// Create takes the representation of a toMetricsRule and creates it.  Returns the server's representation of the toMetricsRule, and an error, if there is any.
func (c *FakeToMetricsRules) Create(ctx context.Context, toMetricsRule *v1alpha1.ToMetricsRule, opts v1.CreateOptions) (result *v1alpha1.ToMetricsRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(tometricsrulesResource, c.ns, toMetricsRule), &v1alpha1.ToMetricsRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ToMetricsRule), err
}

// Update takes the representation of a toMetricsRule and updates it. Returns the server's representation of the toMetricsRule, and an error, if there is any.
func (c *FakeToMetricsRules) Update(ctx context.Context, toMetricsRule *v1alpha1.ToMetricsRule, opts v1.UpdateOptions) (result *v1alpha1.ToMetricsRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(tometricsrulesResource, c.ns, toMetricsRule), &v1alpha1.ToMetricsRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ToMetricsRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeToMetricsRules) UpdateStatus(ctx context.Context, toMetricsRule *v1alpha1.ToMetricsRule, opts v1.UpdateOptions) (*v1alpha1.ToMetricsRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(tometricsrulesResource, "status", c.ns, toMetricsRule), &v1alpha1.ToMetricsRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ToMetricsRule), err
}

// Delete takes name of the toMetricsRule and deletes it. Returns an error if one occurs.
func (c *FakeToMetricsRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(tometricsrulesResource, c.ns, name), &v1alpha1.ToMetricsRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeToMetricsRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(tometricsrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ToMetricsRuleList{})
	return err
}

// Patch applies the patch and returns the patched toMetricsRule.
func (c *FakeToMetricsRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ToMetricsRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(tometricsrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ToMetricsRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ToMetricsRule), err
}
