/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/one/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDashboardRaws implements DashboardRawInterface
type FakeDashboardRaws struct {
	Fake *FakeOneV1alpha1
	ns   string
}

var dashboardrawsResource = schema.GroupVersionResource{Group: "one.newrelic.kubeform.com", Version: "v1alpha1", Resource: "dashboardraws"}

var dashboardrawsKind = schema.GroupVersionKind{Group: "one.newrelic.kubeform.com", Version: "v1alpha1", Kind: "DashboardRaw"}

// Get takes name of the dashboardRaw, and returns the corresponding dashboardRaw object, and an error if there is any.
func (c *FakeDashboardRaws) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DashboardRaw, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dashboardrawsResource, c.ns, name), &v1alpha1.DashboardRaw{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardRaw), err
}

// List takes label and field selectors, and returns the list of DashboardRaws that match those selectors.
func (c *FakeDashboardRaws) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DashboardRawList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dashboardrawsResource, dashboardrawsKind, c.ns, opts), &v1alpha1.DashboardRawList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DashboardRawList{ListMeta: obj.(*v1alpha1.DashboardRawList).ListMeta}
	for _, item := range obj.(*v1alpha1.DashboardRawList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dashboardRaws.
func (c *FakeDashboardRaws) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dashboardrawsResource, c.ns, opts))

}

// Create takes the representation of a dashboardRaw and creates it.  Returns the server's representation of the dashboardRaw, and an error, if there is any.
func (c *FakeDashboardRaws) Create(ctx context.Context, dashboardRaw *v1alpha1.DashboardRaw, opts v1.CreateOptions) (result *v1alpha1.DashboardRaw, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dashboardrawsResource, c.ns, dashboardRaw), &v1alpha1.DashboardRaw{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardRaw), err
}

// Update takes the representation of a dashboardRaw and updates it. Returns the server's representation of the dashboardRaw, and an error, if there is any.
func (c *FakeDashboardRaws) Update(ctx context.Context, dashboardRaw *v1alpha1.DashboardRaw, opts v1.UpdateOptions) (result *v1alpha1.DashboardRaw, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dashboardrawsResource, c.ns, dashboardRaw), &v1alpha1.DashboardRaw{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardRaw), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDashboardRaws) UpdateStatus(ctx context.Context, dashboardRaw *v1alpha1.DashboardRaw, opts v1.UpdateOptions) (*v1alpha1.DashboardRaw, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dashboardrawsResource, "status", c.ns, dashboardRaw), &v1alpha1.DashboardRaw{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardRaw), err
}

// Delete takes name of the dashboardRaw and deletes it. Returns an error if one occurs.
func (c *FakeDashboardRaws) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dashboardrawsResource, c.ns, name), &v1alpha1.DashboardRaw{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDashboardRaws) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dashboardrawsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DashboardRawList{})
	return err
}

// Patch applies the patch and returns the patched dashboardRaw.
func (c *FakeDashboardRaws) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DashboardRaw, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dashboardrawsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DashboardRaw{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DashboardRaw), err
}
