/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/alert/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMutingRules implements MutingRuleInterface
type FakeMutingRules struct {
	Fake *FakeAlertV1alpha1
	ns   string
}

var mutingrulesResource = schema.GroupVersionResource{Group: "alert.newrelic.kubeform.com", Version: "v1alpha1", Resource: "mutingrules"}

var mutingrulesKind = schema.GroupVersionKind{Group: "alert.newrelic.kubeform.com", Version: "v1alpha1", Kind: "MutingRule"}

// Get takes name of the mutingRule, and returns the corresponding mutingRule object, and an error if there is any.
func (c *FakeMutingRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MutingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mutingrulesResource, c.ns, name), &v1alpha1.MutingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutingRule), err
}

// List takes label and field selectors, and returns the list of MutingRules that match those selectors.
func (c *FakeMutingRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MutingRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mutingrulesResource, mutingrulesKind, c.ns, opts), &v1alpha1.MutingRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MutingRuleList{ListMeta: obj.(*v1alpha1.MutingRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MutingRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mutingRules.
func (c *FakeMutingRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mutingrulesResource, c.ns, opts))

}

// Create takes the representation of a mutingRule and creates it.  Returns the server's representation of the mutingRule, and an error, if there is any.
func (c *FakeMutingRules) Create(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.CreateOptions) (result *v1alpha1.MutingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mutingrulesResource, c.ns, mutingRule), &v1alpha1.MutingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutingRule), err
}

// Update takes the representation of a mutingRule and updates it. Returns the server's representation of the mutingRule, and an error, if there is any.
func (c *FakeMutingRules) Update(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (result *v1alpha1.MutingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mutingrulesResource, c.ns, mutingRule), &v1alpha1.MutingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutingRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMutingRules) UpdateStatus(ctx context.Context, mutingRule *v1alpha1.MutingRule, opts v1.UpdateOptions) (*v1alpha1.MutingRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mutingrulesResource, "status", c.ns, mutingRule), &v1alpha1.MutingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutingRule), err
}

// Delete takes name of the mutingRule and deletes it. Returns an error if one occurs.
func (c *FakeMutingRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(mutingrulesResource, c.ns, name), &v1alpha1.MutingRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMutingRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mutingrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MutingRuleList{})
	return err
}

// Patch applies the patch and returns the patched mutingRule.
func (c *FakeMutingRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MutingRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mutingrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MutingRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MutingRule), err
}
