/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/nrql/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDropRules implements DropRuleInterface
type FakeDropRules struct {
	Fake *FakeNrqlV1alpha1
	ns   string
}

var droprulesResource = schema.GroupVersionResource{Group: "nrql.newrelic.kubeform.com", Version: "v1alpha1", Resource: "droprules"}

var droprulesKind = schema.GroupVersionKind{Group: "nrql.newrelic.kubeform.com", Version: "v1alpha1", Kind: "DropRule"}

// Get takes name of the dropRule, and returns the corresponding dropRule object, and an error if there is any.
func (c *FakeDropRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DropRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(droprulesResource, c.ns, name), &v1alpha1.DropRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DropRule), err
}

// List takes label and field selectors, and returns the list of DropRules that match those selectors.
func (c *FakeDropRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DropRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(droprulesResource, droprulesKind, c.ns, opts), &v1alpha1.DropRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DropRuleList{ListMeta: obj.(*v1alpha1.DropRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.DropRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dropRules.
func (c *FakeDropRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(droprulesResource, c.ns, opts))

}

// Create takes the representation of a dropRule and creates it.  Returns the server's representation of the dropRule, and an error, if there is any.
func (c *FakeDropRules) Create(ctx context.Context, dropRule *v1alpha1.DropRule, opts v1.CreateOptions) (result *v1alpha1.DropRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(droprulesResource, c.ns, dropRule), &v1alpha1.DropRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DropRule), err
}

// Update takes the representation of a dropRule and updates it. Returns the server's representation of the dropRule, and an error, if there is any.
func (c *FakeDropRules) Update(ctx context.Context, dropRule *v1alpha1.DropRule, opts v1.UpdateOptions) (result *v1alpha1.DropRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(droprulesResource, c.ns, dropRule), &v1alpha1.DropRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DropRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDropRules) UpdateStatus(ctx context.Context, dropRule *v1alpha1.DropRule, opts v1.UpdateOptions) (*v1alpha1.DropRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(droprulesResource, "status", c.ns, dropRule), &v1alpha1.DropRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DropRule), err
}

// Delete takes name of the dropRule and deletes it. Returns an error if one occurs.
func (c *FakeDropRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(droprulesResource, c.ns, name), &v1alpha1.DropRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDropRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(droprulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DropRuleList{})
	return err
}

// Patch applies the patch and returns the patched dropRule.
func (c *FakeDropRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DropRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(droprulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DropRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DropRule), err
}
