/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertConditionListerExpansion allows custom methods to be added to
// AlertConditionLister.
type AlertConditionListerExpansion interface{}

// AlertConditionNamespaceListerExpansion allows custom methods to be added to
// AlertConditionNamespaceLister.
type AlertConditionNamespaceListerExpansion interface{}

// MonitorListerExpansion allows custom methods to be added to
// MonitorLister.
type MonitorListerExpansion interface{}

// MonitorNamespaceListerExpansion allows custom methods to be added to
// MonitorNamespaceLister.
type MonitorNamespaceListerExpansion interface{}

// MonitorScriptListerExpansion allows custom methods to be added to
// MonitorScriptLister.
type MonitorScriptListerExpansion interface{}

// MonitorScriptNamespaceListerExpansion allows custom methods to be added to
// MonitorScriptNamespaceLister.
type MonitorScriptNamespaceListerExpansion interface{}

// MultilocationAlertConditionListerExpansion allows custom methods to be added to
// MultilocationAlertConditionLister.
type MultilocationAlertConditionListerExpansion interface{}

// MultilocationAlertConditionNamespaceListerExpansion allows custom methods to be added to
// MultilocationAlertConditionNamespaceLister.
type MultilocationAlertConditionNamespaceListerExpansion interface{}

// SecureCredentialListerExpansion allows custom methods to be added to
// SecureCredentialLister.
type SecureCredentialListerExpansion interface{}

// SecureCredentialNamespaceListerExpansion allows custom methods to be added to
// SecureCredentialNamespaceLister.
type SecureCredentialNamespaceListerExpansion interface{}
