/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "kubeform.dev/provider-newrelic-api/client/clientset/versioned"
	alertv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/alert/v1alpha1"
	fakealertv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/alert/v1alpha1/fake"
	apiaccessv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/apiaccess/v1alpha1"
	fakeapiaccessv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/apiaccess/v1alpha1/fake"
	applicationv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/application/v1alpha1"
	fakeapplicationv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/application/v1alpha1/fake"
	dashboardv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/dashboard/v1alpha1"
	fakedashboardv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/dashboard/v1alpha1/fake"
	entityv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/entity/v1alpha1"
	fakeentityv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/entity/v1alpha1/fake"
	eventsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/events/v1alpha1"
	fakeeventsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/events/v1alpha1/fake"
	infrav1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/infra/v1alpha1"
	fakeinfrav1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/infra/v1alpha1/fake"
	insightsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/insights/v1alpha1"
	fakeinsightsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/insights/v1alpha1/fake"
	nrqlv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/nrql/v1alpha1"
	fakenrqlv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/nrql/v1alpha1/fake"
	onev1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/one/v1alpha1"
	fakeonev1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/one/v1alpha1/fake"
	pluginsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/plugins/v1alpha1"
	fakepluginsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/plugins/v1alpha1/fake"
	servicev1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/service/v1alpha1"
	fakeservicev1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/service/v1alpha1/fake"
	syntheticsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/synthetics/v1alpha1"
	fakesyntheticsv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/synthetics/v1alpha1/fake"
	workloadv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/workload/v1alpha1"
	fakeworkloadv1alpha1 "kubeform.dev/provider-newrelic-api/client/clientset/versioned/typed/workload/v1alpha1/fake"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// AlertV1alpha1 retrieves the AlertV1alpha1Client
func (c *Clientset) AlertV1alpha1() alertv1alpha1.AlertV1alpha1Interface {
	return &fakealertv1alpha1.FakeAlertV1alpha1{Fake: &c.Fake}
}

// ApiaccessV1alpha1 retrieves the ApiaccessV1alpha1Client
func (c *Clientset) ApiaccessV1alpha1() apiaccessv1alpha1.ApiaccessV1alpha1Interface {
	return &fakeapiaccessv1alpha1.FakeApiaccessV1alpha1{Fake: &c.Fake}
}

// ApplicationV1alpha1 retrieves the ApplicationV1alpha1Client
func (c *Clientset) ApplicationV1alpha1() applicationv1alpha1.ApplicationV1alpha1Interface {
	return &fakeapplicationv1alpha1.FakeApplicationV1alpha1{Fake: &c.Fake}
}

// DashboardV1alpha1 retrieves the DashboardV1alpha1Client
func (c *Clientset) DashboardV1alpha1() dashboardv1alpha1.DashboardV1alpha1Interface {
	return &fakedashboardv1alpha1.FakeDashboardV1alpha1{Fake: &c.Fake}
}

// EntityV1alpha1 retrieves the EntityV1alpha1Client
func (c *Clientset) EntityV1alpha1() entityv1alpha1.EntityV1alpha1Interface {
	return &fakeentityv1alpha1.FakeEntityV1alpha1{Fake: &c.Fake}
}

// EventsV1alpha1 retrieves the EventsV1alpha1Client
func (c *Clientset) EventsV1alpha1() eventsv1alpha1.EventsV1alpha1Interface {
	return &fakeeventsv1alpha1.FakeEventsV1alpha1{Fake: &c.Fake}
}

// InfraV1alpha1 retrieves the InfraV1alpha1Client
func (c *Clientset) InfraV1alpha1() infrav1alpha1.InfraV1alpha1Interface {
	return &fakeinfrav1alpha1.FakeInfraV1alpha1{Fake: &c.Fake}
}

// InsightsV1alpha1 retrieves the InsightsV1alpha1Client
func (c *Clientset) InsightsV1alpha1() insightsv1alpha1.InsightsV1alpha1Interface {
	return &fakeinsightsv1alpha1.FakeInsightsV1alpha1{Fake: &c.Fake}
}

// NrqlV1alpha1 retrieves the NrqlV1alpha1Client
func (c *Clientset) NrqlV1alpha1() nrqlv1alpha1.NrqlV1alpha1Interface {
	return &fakenrqlv1alpha1.FakeNrqlV1alpha1{Fake: &c.Fake}
}

// OneV1alpha1 retrieves the OneV1alpha1Client
func (c *Clientset) OneV1alpha1() onev1alpha1.OneV1alpha1Interface {
	return &fakeonev1alpha1.FakeOneV1alpha1{Fake: &c.Fake}
}

// PluginsV1alpha1 retrieves the PluginsV1alpha1Client
func (c *Clientset) PluginsV1alpha1() pluginsv1alpha1.PluginsV1alpha1Interface {
	return &fakepluginsv1alpha1.FakePluginsV1alpha1{Fake: &c.Fake}
}

// ServiceV1alpha1 retrieves the ServiceV1alpha1Client
func (c *Clientset) ServiceV1alpha1() servicev1alpha1.ServiceV1alpha1Interface {
	return &fakeservicev1alpha1.FakeServiceV1alpha1{Fake: &c.Fake}
}

// SyntheticsV1alpha1 retrieves the SyntheticsV1alpha1Client
func (c *Clientset) SyntheticsV1alpha1() syntheticsv1alpha1.SyntheticsV1alpha1Interface {
	return &fakesyntheticsv1alpha1.FakeSyntheticsV1alpha1{Fake: &c.Fake}
}

// WorkloadV1alpha1 retrieves the WorkloadV1alpha1Client
func (c *Clientset) WorkloadV1alpha1() workloadv1alpha1.WorkloadV1alpha1Interface {
	return &fakeworkloadv1alpha1.FakeWorkloadV1alpha1{Fake: &c.Fake}
}
