/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-newrelic-api/apis/synthetics/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMultilocationAlertConditions implements MultilocationAlertConditionInterface
type FakeMultilocationAlertConditions struct {
	Fake *FakeSyntheticsV1alpha1
	ns   string
}

var multilocationalertconditionsResource = schema.GroupVersionResource{Group: "synthetics.newrelic.kubeform.com", Version: "v1alpha1", Resource: "multilocationalertconditions"}

var multilocationalertconditionsKind = schema.GroupVersionKind{Group: "synthetics.newrelic.kubeform.com", Version: "v1alpha1", Kind: "MultilocationAlertCondition"}

// Get takes name of the multilocationAlertCondition, and returns the corresponding multilocationAlertCondition object, and an error if there is any.
func (c *FakeMultilocationAlertConditions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MultilocationAlertCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(multilocationalertconditionsResource, c.ns, name), &v1alpha1.MultilocationAlertCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultilocationAlertCondition), err
}

// List takes label and field selectors, and returns the list of MultilocationAlertConditions that match those selectors.
func (c *FakeMultilocationAlertConditions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MultilocationAlertConditionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(multilocationalertconditionsResource, multilocationalertconditionsKind, c.ns, opts), &v1alpha1.MultilocationAlertConditionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MultilocationAlertConditionList{ListMeta: obj.(*v1alpha1.MultilocationAlertConditionList).ListMeta}
	for _, item := range obj.(*v1alpha1.MultilocationAlertConditionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested multilocationAlertConditions.
func (c *FakeMultilocationAlertConditions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(multilocationalertconditionsResource, c.ns, opts))

}

// Create takes the representation of a multilocationAlertCondition and creates it.  Returns the server's representation of the multilocationAlertCondition, and an error, if there is any.
func (c *FakeMultilocationAlertConditions) Create(ctx context.Context, multilocationAlertCondition *v1alpha1.MultilocationAlertCondition, opts v1.CreateOptions) (result *v1alpha1.MultilocationAlertCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(multilocationalertconditionsResource, c.ns, multilocationAlertCondition), &v1alpha1.MultilocationAlertCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultilocationAlertCondition), err
}

// Update takes the representation of a multilocationAlertCondition and updates it. Returns the server's representation of the multilocationAlertCondition, and an error, if there is any.
func (c *FakeMultilocationAlertConditions) Update(ctx context.Context, multilocationAlertCondition *v1alpha1.MultilocationAlertCondition, opts v1.UpdateOptions) (result *v1alpha1.MultilocationAlertCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(multilocationalertconditionsResource, c.ns, multilocationAlertCondition), &v1alpha1.MultilocationAlertCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultilocationAlertCondition), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMultilocationAlertConditions) UpdateStatus(ctx context.Context, multilocationAlertCondition *v1alpha1.MultilocationAlertCondition, opts v1.UpdateOptions) (*v1alpha1.MultilocationAlertCondition, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(multilocationalertconditionsResource, "status", c.ns, multilocationAlertCondition), &v1alpha1.MultilocationAlertCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultilocationAlertCondition), err
}

// Delete takes name of the multilocationAlertCondition and deletes it. Returns an error if one occurs.
func (c *FakeMultilocationAlertConditions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(multilocationalertconditionsResource, c.ns, name), &v1alpha1.MultilocationAlertCondition{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMultilocationAlertConditions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(multilocationalertconditionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MultilocationAlertConditionList{})
	return err
}

// Patch applies the patch and returns the patched multilocationAlertCondition.
func (c *FakeMultilocationAlertConditions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MultilocationAlertCondition, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(multilocationalertconditionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MultilocationAlertCondition{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MultilocationAlertCondition), err
}
